version: '3'
services:
  sql:
    container_name: sql
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: yourStrong(!)Password
    networks:
    - "default"
    volumes:
      - "mssqlsystem:/var/opt/mssql"
      - "mssqluser:/var/opt/sqlserver"
    restart: always
  web_api: 
    container_name: web_api
    image: leroman/diary_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_PASSWORD=${DB_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_KEY=${JWT_KEY}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports: 
      - "5129:8080"
    networks:
    - "default"
    restart: always
  frontend_ng: 
    container_name: frontend_ng
    image: leroman/diary_ng
    ports: 
      - "80:80" 
    networks:
    - "default"
    restart: always 
networks:
  default:
    driver: bridge
volumes:
  mssqlsystem:
    external: true
  mssqluser: 
    external: true